-- Loaded/source tables. These are populated by DBMapper migration.
SELECT 'loaded/source' AS layer, 'customer' AS table_name, COUNT(*) AS row_count FROM "customer";
SELECT 'loaded/source' AS layer, 'product' AS table_name, COUNT(*) AS row_count FROM "product";
SELECT 'loaded/source' AS layer, 'order' AS table_name, COUNT(*) AS row_count FROM "order";

-- dbt staging views. These are generated by dbt and read from loaded/source tables.
SELECT 'dbt staging' AS layer, 'stg_customer' AS table_name, COUNT(*) AS row_count FROM "stg_customer";
SELECT 'dbt staging' AS layer, 'stg_product' AS table_name, COUNT(*) AS row_count FROM "stg_product";
SELECT 'dbt staging' AS layer, 'stg_order' AS table_name, COUNT(*) AS row_count FROM "stg_order";

-- dbt mart tables. These are generated by dbt build.
SELECT 'dbt mart' AS layer, 'mart_customer' AS table_name, COUNT(*) AS row_count FROM "mart_customer";
SELECT 'dbt mart' AS layer, 'mart_product' AS table_name, COUNT(*) AS row_count FROM "mart_product";
SELECT 'dbt mart' AS layer, 'mart_order' AS table_name, COUNT(*) AS row_count FROM "mart_order";
SELECT 'dbt mart' AS layer, 'mart_order_enriched' AS table_name, COUNT(*) AS row_count FROM "mart_order_enriched";
